server:
  port: 8761

spring:
  application:
    name: discovery-server

  config:
    import: optional:configserver:http://localhost:8888

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka/

  server:
    enable-self-preservation: false
    peer-node-read-timeout-ms: 20000

logging:
  level:
    root: INFO
    com.funride: DEBUG
