server:
  port: 8888

spring:
  application:
    name: config-server

  profiles:
    active: native

  cloud:
    config:
      server:
        native:
          search-locations: file:///C:\Users\adars\Karnics-Fundride-Backend\centralized-config

logging:
  level:
    root: INFO
    com.funride: DEBUG