
spring:
  datasource:
    url: jdbc:postgresql://103.174.103.250:5432/funride
    username: postgres
    password: S@b8at1zedbpostgres

    hikari:
      max-lifetime: 300000
      keepalive-time: 30000


      jpa:
        hibernate:
          ddl-auto: update


  #redis:
#  host: localhost
#  port: 6379



  data:
    redis:
      host: localhost
      port: 6379

razorpay:
  key: YOUR_KEY
  secret: YOUR_SECRET
